# -*- coding: utf-8 -*-
"""重新生成 romannum_bitmap.h: LSB-first 打包 (xbm 格式, drawXBitmap 要求)"""
import numpy as np
from PIL import Image, ImageDraw, ImageFont

SIZE = 240
OUT = r'src/romannum_bitmap.h'
font = ImageFont.truetype(r'C:\Windows\Fonts\arialbd.ttf', SIZE)

def render_char(code):
    ch = chr(code)
    img = Image.new('L', (SIZE + 100, SIZE + 120), 255)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=0)
    a = np.array(img); bw = a < 128
    nz = np.where(bw)
    if len(nz[0]) == 0: return None
    x0, y0 = int(nz[1].min()), int(nz[0].min())
    x1, y1 = int(nz[1].max()) + 1, int(nz[0].max()) + 1
    return bw[y0:y1, x0:x1]

def pack_bitmap(mask):
    h, w = mask.shape
    nbytes = (w + 7) // 8
    rows = []
    for y in range(h):
        for b in range(nbytes):
            byte = 0
            for bit in range(8):
                i = b * 8 + bit
                if i < w and mask[y][i]:
                    byte |= (1 << bit)  # LSB first: bit0 = 左边第一个像素 (xbm 格式)
            rows.append(byte)
    return bytes(rows)

DIGITS = '0123456789'
def cname(code):
    return 'rnum_colon' if code == 0x3A else 'rnum_%s' % DIGITS[code - 0x30]

lines = []
lines.append('// 240px Arial Bold big-digit bitmaps, generated by tools/gen_romannum_bitmap.py')
lines.append('// xbm format (LSB-first, for drawXBitmap). Each glyph has its OWN width/height.')
lines.append('#ifndef __ROMANNUM_BITMAP_H__')
lines.append('#define __ROMANNUM_BITMAP_H__')
lines.append('#include <stdint.h>')
lines.append('')

meta = {}
for code in list(range(0x30, 0x3A)) + [0x3A]:
    mask = render_char(code)
    w, h = mask.shape[1], mask.shape[0]
    data = pack_bitmap(mask)
    meta[code] = (cname(code), w, h, len(data))
    lines.append('static const uint8_t %s[] = {' % cname(code))
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append('    ' + ','.join('0x%02X' % b for b in chunk) + ',')
    lines.append('};')
    lines.append('')

lines.append('// proportional width & height per char')
for i in range(10):
    code = 0x30 + i
    name, w, h, _ = meta[code]
    lines.append('#define RNUM_%s_W %d' % (DIGITS[i], w))
    lines.append('#define RNUM_%s_H %d' % (DIGITS[i], h))
lines.append('#define RNUM_COLON_W %d' % meta[0x3A][1])
lines.append('#define RNUM_COLON_H %d' % meta[0x3A][2])
lines.append('')
lines.append('// return bitmap/width/height for a char, nullptr if unsupported')
lines.append('static inline const uint8_t *rnum_glyph(uint8_t ch, uint16_t &w, uint16_t &h) {')
lines.append('    switch (ch) {')
for i in range(10):
    code = 0x30 + i
    name, nw, nh, _ = meta[code]
    lines.append("        case '%d': w = RNUM_%s_W; h = RNUM_%s_H; return %s;" % (i, DIGITS[i], DIGITS[i], name))
lines.append("        case ':': w = RNUM_COLON_W; h = RNUM_COLON_H; return rnum_colon;")
lines.append('        default: w = 0; h = 0; return nullptr;')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('#endif // __ROMANNUM_BITMAP_H__')

open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
print('generated', OUT)
print('sizes:', {k: (v[1], v[2]) for k, v in meta.items()})